"""added categories and priorities

Revision ID: 1206fc6b61ec
Revises: 3df70ffc8d95
Create Date: 2025-10-08 00:02:44.049288

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1206fc6b61ec"
down_revision = "3df70ffc8d95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "todo_category",
        sa.Column("todo_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["todo_id"],
            ["todo.id"],
        ),
        sa.PrimaryKeyConstraint("todo_id", "category_id"),
    )
    with op.batch_alter_table("todo", schema=None) as batch_op:
        # Add priority column as nullable first
        batch_op.add_column(
            sa.Column(
                "priority", sa.Enum("A", "B", "C", name="priority"), nullable=True
            )
        )
        batch_op.alter_column(
            "date_created", existing_type=sa.DATETIME(), nullable=False
        )

    # Set default priority 'C' for all existing rows
    op.execute("UPDATE todo SET priority = 'C' WHERE priority IS NULL")

    # Now make priority non-nullable
    with op.batch_alter_table("todo", schema=None) as batch_op:
        batch_op.alter_column("priority", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todo", schema=None) as batch_op:
        batch_op.alter_column(
            "date_created", existing_type=sa.DATETIME(), nullable=True
        )
        batch_op.drop_column("priority")

    op.drop_table("todo_category")
    op.drop_table("category")
    # ### end Alembic commands ###
